services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: camp-backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      PORT: 5000
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 8

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camp-frontend
    ports:
      - "8088:80"
    depends_on:
      backend:
        condition: service_healthy

